### ISSUE TITLE
[Bug] Translations on the profile page don't load when you go from the nav

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1173] opened 2022-11-24 08:45 UTC
**Describe the bug**
When you go to your profile page from the navigation the translations are not loaded, but once you refresh the page they are.

**Screenshots**:
![profile-translation-bug pdf](https://user-images.githubusercontent.com/61479393/203735294-6e04b349-9a0f-43cc-809e-1989bf715c80.gif)

**To Reproduce**

1. Go to the homepage
2. Log in
3. Click on your avatar and then on My Profile
5. See the translations not loading
6. Refresh the page and see the translations load

**Desktop (please complete the following information):**

- OS: MacOS Ventura
- Browser Chrome
- Version 108

**Comment by kachar** [comment] 2022-11-27 09:45
Duplicate of #1187

**Closed by kachar** 2022-11-27 09:45 UTC
Labels: bug
