### ISSUE TITLE
Images aren't loading after navigating through the site a bit

### ISSUE THREAD

**Issue by MartinaMitz** [podkrepi-bg/frontend#1549] opened 2023-08-09 16:46 UTC
### Which area(s) of Podkrepi.bg are affected?

Images

### Describe the Bug

After a while, when navigating through the website, all images start showing as broken links even when clicking on different pages (e.g. homepages, all campaigns). It only resolves when one refreshes the website.
<img width="1052" alt="Screenshot 2023-08-09 at 19 43 17" src="https://github.com/podkrepi-bg/frontend/assets/132821177/c9c9c153-0b48-43da-b57c-14f57d1116fd">

### To Reproduce

when navigating through the website, all images start showing as broken links

### Expected Behavior

Images should load even with lower bandwidth (11 Mbps)

### Which browser are you using? (if relevant)

Chrome Version 114.0.5735.248 (Official Build) (arm64)

**Comment by MartinaMitz** [comment] 2023-08-09 17:31
Unfortunately, I can't tell a particular sequence... it appears to be rather at random, but happens at least once every day.

**Comment by slavcho** [comment] 2023-08-09 18:31
@MartinaMitz  are you by any chance using a VPN or something of sort?

**Comment by MartinaMitz** [comment] 2023-08-09 19:12
No @slavcho , I am not.
Will upload a screen recording in the front-end channel too, as it's too big to add here.

**Comment by slavcho** [comment] 2023-08-11 07:15
Since we cannot reproduce this.
Please ping me on discord if you experience it again. We will do debugging in real time.

**Comment by ani-kalpachka** [comment] 2023-08-12 14:02
I tested on Chrome and Firefox browsers on desktop and mobile device and I could not reproduce such issue.

**Comment by igoychev** [comment] 2023-09-12 06:23
closing as fixed after the latest improvements, pls open new one if it happens again

**Closed by igoychev** 2023-09-12 06:23 UTC
Labels: type: bug
