### ISSUE TITLE
[Bug] - Montserrat font is not supported by Firefox

### ISSUE THREAD

**Issue by StanislavSt** [podkrepi-bg/frontend#1004] opened 2022-08-24 13:02 UTC
**Describe the bug**
Montserrat font is not compatible with Firefox. Website looks different on Firefox vs Chrome/Safari. 
Suggestion - switch to a CCS safe type of font, that renders equally on all browser engines.  - https://www.cssfontstack.com/

Firefox render of the website - 
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/12186099/186424183-011d8f26-7fee-4938-8b6e-1557be7207aa.png">

Chrome render of the website - 
<img width="1666" alt="image" src="https://user-images.githubusercontent.com/12186099/186424316-fd24a564-dcdd-4f4d-8712-f987780af008.png">

**Comment by ani-kalpachka** [comment] 2022-11-21 18:21
I cannot reproduce the issue. The font in Firefox is currently Montserrat and the texts look identical for all browsers:

![4](https://user-images.githubusercontent.com/14351733/203130721-55ab0051-9bae-48da-b0c7-afc6adc4cff2.png)

I am closing the issue. Please reopen in case of misunderstanding.

**Closed by ani-kalpachka** 2022-11-21 18:21 UTC
Labels: bug, request for comments, frontend
