### ISSUE TITLE
[Bug] Create campaign form - beneficiary and coordinator

### ISSUE THREAD

**Issue by dplamenov** [podkrepi-bg/frontend#628] opened 2022-03-18 14:09 UTC
**Describe the bug**
Validation of the campaign creation form and the API server expect to have a `beneficiaryId` and a `coordinatorId` in the request, which should be UUID. But there is no possibility to enter UUIDs in the form. The form has only two modals that allow entering name, email and phone, but no UUIDs.

**To Reproduce**

1. Go to `campaigns/create`
2. Try to create new campaign

**Screenshots**
![Screenshot at Mar 18 16-06-05](https://user-images.githubusercontent.com/30602242/159017760-c67ef050-a678-4b6b-a75d-6bcee890bb05.png)
This is the modal for coordinator but form and API server expect `coordinatorId`:
![Screenshot at Mar 18 16-06-19](https://user-images.githubusercontent.com/30602242/159018030-44b49d7c-514c-43b5-8415-33a76a353399.png)

 @igoychev @kachar @imilchev

**Comment by kachar** [comment] 2022-03-18 16:25
Kind of duplicate of https://github.com/podkrepi-bg/frontend/issues/362

**Comment by ani-kalpachka** [comment] 2022-10-22 19:40
Closing the ticket as a duplicate of #364.

**Closed by ani-kalpachka** 2022-10-22 19:40 UTC
Labels: bug
