### ISSUE TITLE
[Bug] Some contents on the site are not being translated

### ISSUE THREAD

**Issue by Olaleye-Blessing** [podkrepi-bg/frontend#1066] opened 2022-10-19 09:57 UTC
**Describe the bug**
The FAQs on the home and FAQ pages are not translated after switching to `EN`.

**To Reproduce**

For the home page
1. Go to [home page](https://podkrepi.bg/en).
2. Scroll down to the `Frequently Asked Questions` section.
3. See the error

For FAQ page
1. Go to [FAQ page](https://podkrepi.bg/en/faq)
2. See the error

**Expected behavior**
The FAQ section on the home and FAQ pages should be translated after switching to English.

**Screenshots**

![Screenshot (136)](https://user-images.githubusercontent.com/70102539/196658641-6f3cc8b0-0488-4cb4-8faa-1ca61db51521.png)

![Screenshot (137)](https://user-images.githubusercontent.com/70102539/196658659-fd3963c8-df77-48e8-b6f0-a535fa6b5e5c.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: brave
- Version: 10

**Comment by valkirilov** [comment] 2022-11-20 09:19
Note: It's not a bug with the website itself, instead there are no translations for this section at all:
- we have to translate all questions in English
- we have to apply some changes in the codebase so it will use i18n keys and automatically show the correct text according to the selected language instead of using only the hard-coded Bulgarian text

**Comment by ani-kalpachka** [comment] 2022-11-28 19:09
Closing this issue since it is reported as part of https://github.com/podkrepi-bg/frontend/issues/1066.

**Closed by ani-kalpachka** 2022-11-28 19:09 UTC
Labels: bug
