### ISSUE TITLE
[CreateCampaign] Step process for Campaign Creation

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#437] opened 2022-01-16 17:27 UTC
As per the design here: 
https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=7690%3A23718

We need to have a step-by-step campaign creation process. Create a stepper in the same way as the Support Us registration: https://dev.podkrepi.bg/support

Task Breakdown
- [ ] Create the Stepper
- [ ] Create Organizer Step
- [ ] Select Beneficiery Step
- [ ] Fill Campaign Details and Docs/Image Upload Step

**Comment by nradkova** [comment] 2022-04-14 13:20
[https://github.com/podkrepi-bg/frontend/tree/campaign-form-beneficiary-coordinator](url)

### So far created:
- stepper structure
- page layouts for each step
- partial validation
- data state preserved through steps

### Has to be done:
- validation for details page 
- file uploading functionality
-  extracting and modeling needed data for a create request
- success or error message on submitting the request

**Comment by slavcho** [comment] 2024-05-22 07:32
Closing as duplicate of #1388

**Closed by slavcho** 2024-05-22 07:32 UTC
