### ISSUE TITLE
[Bug] [Medium] Theres no landing page on the Home Page "Спешни кампании" cards 

### ISSUE THREAD

**Issue by petarrr1** [podkrepi-bg/frontend#936] opened 2022-07-26 13:01 UTC
**Describe the bug**
Placing the mouse on the cards the cursor changes to a link pointer, but clicking does not redirect anywhere.

**To Reproduce**

1. Go to 'HomePage'
2. Place the mouse on one of the cards at "Нашите кампании"
3. Click

**Expected behavior**

Redirecting to the campaign page, probably the same direction as the "Вижте повече" button.
The link pointer will only show up when there is a link to follow.

**Actual behavior**

Clicking on the cards nothing happens.

Desktop:
OS: macOS Catalina 10.15.7 
Browser: safari
Version [15.4]

**Comment by imilchev** [comment] 2022-07-28 21:32
There is no error. It just doesn't redirect. I am closing this as duplicate of #946 which is resolved in #948. Please re-open the issue if I didn't understand it correctly

**Closed by imilchev** 2022-07-28 21:32 UTC
Labels: bug
