### ISSUE TITLE
Blog - Broken Image in Blog Article

### ISSUE THREAD

**Issue by FlyWithMarie** [podkrepi-bg/frontend#1808] opened 2024-05-24 13:15 UTC
### Which area(s) of Podkrepi.bg are affected?

Images, Blog

### Describe the Bug

There is a broken image in the following blog article:
https://podkrepi.bg/en/blog/s-kakvo-sie-otlichava-podkriepi-bgh-kato-daritielska-platforma

### To Reproduce

1. Open https://podkrepi.bg/blog
2. Select "С какво се отличава Подкрепи бг като дарителска платформа?" Blog Article
3. Scroll down to find the broken image.

Alternatively, you can follow this url to the blog post in question:
https://podkrepi.bg/blog/s-kakvo-sie-otlichava-podkriepi-bgh-kato-daritielska-platforma
![BrokenImage1](https://github.com/podkrepi-bg/frontend/assets/158328628/09872a39-d9e6-47ca-9446-ddb2d7b70369)
![BrokenImage2](https://github.com/podkrepi-bg/frontend/assets/158328628/12097386-bc33-49b3-a590-43e9540c9240)

### Expected Behavior

Image is visible.

### Which browser are you using? (if relevant)

Chrome: Version 123.0.6312.106 (Official Build) (64-bit), Mozilla: 124.0.2 (64-bit)

**Comment by ani-kalpachka** [comment] 2024-08-05 04:29
Closing as duplicate of https://github.com/podkrepi-bg/frontend/issues/1809

**Closed by ani-kalpachka** 2024-08-05 04:29 UTC
Labels: type: bug, area: blog
