### ISSUE TITLE
Not possible to subscribe for campaign

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1788] opened 2024-05-17 13:49 UTC
### Which area(s) of Podkrepi.bg are affected?

Subscribtion for campaign

### Describe the Bug

Not possible to subscribe for campaign after click button subscribe.

### To Reproduce

https://github.com/podkrepi-bg/frontend/assets/16596102/59a293d6-a380-441d-8c59-14f707299e9a

1. Login with random user in [https://podkrepi.bg/en](https://podkrepi.bg/en)
2. Open [https://podkrepi.bg/en/campaigns/krizisen-centur-za-postradali-ot-nasilie-gr-pernik-shans-za-nov-zhivot](https://podkrepi.bg/en/campaigns/krizisen-centur-za-postradali-ot-nasilie-gr-pernik-shans-za-nov-zhivot)
3. Click button Subscribe for email notifications for the campaign
4. Click button on profile one
5. **Thrown Internal server error**

### Expected Behavior

Subscribe for this email notification

### Which browser are you using? (if relevant)

Floorp Brave Vivaldi

**Comment by sashko9807** [comment] 2024-05-17 19:25
Looks like a duplicate of #1770. Please confirm if that is the case.

**Comment by Tuscann** [comment] 2024-05-17 19:30
I think is the same bug.

**Closed** 2024-05-17 19:32 UTC
Labels: type: bug
