### ISSUE TITLE
[Bug] After registering with new email format is not transpiled properly

### ISSUE THREAD

**Issue by amartyaroy** [podkrepi-bg/frontend#1193] opened 2022-11-27 04:53 UTC
![image](https://user-images.githubusercontent.com/38670066/204119834-68c786a9-1948-4eac-a7bb-f930273d981c.png)

**Comment by kachar** [comment] 2022-11-27 09:44
Duplicate of #1187

**Closed by kachar** 2022-11-27 09:44 UTC
Labels: bug
