### ISSUE TITLE
Different text aligment in columns in same table.

### ISSUE THREAD

**Issue by Tuscann** [podkrepi-bg/frontend#1797] opened 2024-05-22 10:19 UTC
### Which area(s) of Podkrepi.bg are affected?

Desktop layout

### Describe the Bug

![image](https://github.com/podkrepi-bg/frontend/assets/16596102/09bb2165-0461-4644-b9ad-ca30a8bdadbc)

Different text aligment in columns in same table.

### To Reproduce

1. Open [https://podkrepi.bg/campaigns/da-sbudnem-mechtata-na-valeriya-da-vleze-v-top-5-na-evropa-v-tenisa](https://podkrepi.bg/campaigns/da-sbudnem-mechtata-na-valeriya-da-vleze-v-top-5-na-evropa-v-tenisa)
2. Check position of text in column Amount and text in column Attached files
3. Why text aligment is right in column amount but Attached files are left aligment?

### Expected Behavior

All columns to have right Aligment or same Aligment.

### Which browser are you using? (if relevant)

Vivaldi  Floorp

**Comment by ani-kalpachka** [comment] 2024-07-15 06:43
The issue is fixed on production:
![image](https://github.com/user-attachments/assets/f7bead08-17c5-4817-b791-90c68866788c)

Closing it as completed.

**Closed by ani-kalpachka** 2024-07-15 06:43 UTC
Labels: type: bug
